version: '3.8'

services:
  garden-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: garden-bot:${TAG:-latest}
    container_name: garden-bot
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s